---
- hosts: instances
  remote_user: root
  gather_facts: no
  tasks:

    - import_role:
        name: virt_setup
      tags:
        - setup

    - name: Wait for host connection
      wait_for_connection:
        delay: 60
        timeout: 300
      tags:
        - wait

    - import_role:
        name: docker_disk
      tags:
        - docker_disk

    - import_role:
        name: docker_registry
      when: "'docker_registries' in group_names"
      tags:
        - docker_registry
